# Site settings
title: Curious Y
SEOTitle: Curious Y
header-img: img/home-bg.jpg
email: devduyan@gmail.com
description: "개발 공부 기록 | Java developer"
keyword: "java, spring, web, react, javascript"
url: "https://duyankim.github.io" # your host, for absolute URL
baseurl: # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
#weibo_username:
#zhihu_username:
github_username: duyankim
#twitter_username:   huxpro
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
# ["jekyll-paginate", "jekyll-sitemap", "jekyll-include-cache", "jekyll-gist", "jekyll-mermaid"]
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-gist
  - jekyll-mermaid

# mermaid:
#   src: 'path/to/mermaid.js'

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: Yan

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: "UA-196501312-1" # Format: UA-xxxxxx-xx
ga_domain: duyankim.github.io

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "만드는 즐거움. 기록하는 즐거움. 익히는 즐거움 😉 "
sidebar-avatar: /img/nyancat.gif # use absolute URL, seeing it's used in both `/` and `/about/`
widgets:
  - visitor
  - featured-tags
  - short-about
  - recent-posts
  - archive
  - category
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 2 # A tag will be featured if the size of it is more than this condition value
archive_type: "monthly"
show_count: true

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false
# Friends
#friends: [
#    {
#     title: "Su",
#     href: "http://su.gallery/"
# },{
#title: "乱序（Midare）",
#href: "http://mida.re/",
#    },
#  ]
